import type { SupabaseClient } from "@supabase/supabase-js";

export async function createSampleListings(supabase: SupabaseClient, adminId: string) {
  // Get category IDs
  const { data: categories } = await supabase.from("categories").select("id, slug");
  
  if (!categories) return;
  
  const getCategoryId = (slug: string) => categories.find(c => c.slug === slug)?.id;

  const sampleListings = [
    {
      owner_id: adminId,
      category_id: getCategoryId("tecnologia"),
      title: "Ping Soluções",
      slug: "pingsolucoes",
      description: "Soluções completas em tecnologia para sua empresa. Desenvolvimento de software, suporte técnico, consultoria em TI e muito mais. Atendemos empresas de todos os portes.",
      phone_primary: "4133333333",
      phone_whatsapp: "5541999999999",
      email: "contato@pingsolucoes.com.br",
      website: "https://pingsolucoes.com.br",
      address_full: "Rua das Flores, 123, Sala 45, Centro",
      city: "Curitiba",
      state: "PR",
      postal_code: "80010-000",
      status: "active",
      plan_tier: "premium",
      is_verified: true,
      average_rating: 4.8,
      review_count: 24,
      view_count: 1250,
      contact_count: 89,
      business_hours: {
        monday: { open: "08:00", close: "18:00" },
        tuesday: { open: "08:00", close: "18:00" },
        wednesday: { open: "08:00", close: "18:00" },
        thursday: { open: "08:00", close: "18:00" },
        friday: { open: "08:00", close: "18:00" },
        saturday: null,
        sunday: null,
      },
      seo_title: "Ping Soluções - Tecnologia e Inovação em Curitiba",
      seo_description: "Empresa de tecnologia em Curitiba especializada em desenvolvimento de software, suporte técnico e consultoria em TI.",
    },
    {
      owner_id: adminId,
      category_id: getCategoryId("dentistas"),
      title: "Dr. Silva Odontologia",
      slug: "dr-silva-odontologia",
      description: "Clínica odontológica com mais de 15 anos de experiência. Oferecemos tratamentos de ortodontia, implantes, clareamento dental e muito mais.",
      phone_primary: "4132222222",
      phone_whatsapp: "5541988888888",
      email: "contato@drsilva.com.br",
      website: "https://drsilvaodontologia.com.br",
      address_full: "Av. Brasil, 500, Sala 12, Batel",
      city: "Curitiba",
      state: "PR",
      postal_code: "80420-000",
      status: "active",
      plan_tier: "basic",
      is_verified: true,
      average_rating: 4.9,
      review_count: 67,
      view_count: 2340,
      contact_count: 156,
      business_hours: {
        monday: { open: "08:00", close: "19:00" },
        tuesday: { open: "08:00", close: "19:00" },
        wednesday: { open: "08:00", close: "19:00" },
        thursday: { open: "08:00", close: "19:00" },
        friday: { open: "08:00", close: "19:00" },
        saturday: { open: "08:00", close: "13:00" },
        sunday: null,
      },
      seo_title: "Dr. Silva Odontologia - Dentista em Curitiba",
      seo_description: "Clínica odontológica em Curitiba. Ortodontia, implantes, clareamento e mais.",
    },
    {
      owner_id: adminId,
      category_id: getCategoryId("mecanicos"),
      title: "Auto Center Premium",
      slug: "auto-center-premium",
      description: "Oficina mecânica completa com serviços de manutenção preventiva, troca de óleo, alinhamento, balanceamento, suspensão e muito mais.",
      phone_primary: "4131111111",
      phone_whatsapp: "5541977777777",
      email: "contato@autocenterpremium.com.br",
      address_full: "Rua XV de Novembro, 1000, Centro",
      city: "Curitiba",
      state: "PR",
      postal_code: "80060-000",
      status: "active",
      plan_tier: "free",
      is_verified: false,
      average_rating: 4.5,
      review_count: 42,
      view_count: 890,
      contact_count: 67,
      business_hours: {
        monday: { open: "07:30", close: "18:00" },
        tuesday: { open: "07:30", close: "18:00" },
        wednesday: { open: "07:30", close: "18:00" },
        thursday: { open: "07:30", close: "18:00" },
        friday: { open: "07:30", close: "18:00" },
        saturday: { open: "08:00", close: "12:00" },
        sunday: null,
      },
      seo_title: "Auto Center Premium - Mecânica em Curitiba",
      seo_description: "Oficina mecânica em Curitiba. Manutenção preventiva, troca de óleo, alinhamento e balanceamento.",
    },
    {
      owner_id: adminId,
      category_id: getCategoryId("restaurantes"),
      title: "Sabor da Casa",
      slug: "sabor-da-casa",
      description: "Restaurante de comida caseira com buffet por quilo. Pratos típicos da culinária brasileira preparados com ingredientes frescos.",
      phone_primary: "4134444444",
      phone_whatsapp: "5541966666666",
      email: "contato@sabordacasa.com.br",
      address_full: "Rua Marechal Deodoro, 300, Centro",
      city: "Curitiba",
      state: "PR",
      postal_code: "80010-010",
      status: "active",
      plan_tier: "premium",
      is_verified: true,
      average_rating: 4.7,
      review_count: 156,
      view_count: 3200,
      contact_count: 234,
      business_hours: {
        monday: { open: "11:00", close: "15:00" },
        tuesday: { open: "11:00", close: "15:00" },
        wednesday: { open: "11:00", close: "15:00" },
        thursday: { open: "11:00", close: "15:00" },
        friday: { open: "11:00", close: "15:00" },
        saturday: { open: "11:30", close: "15:00" },
        sunday: null,
      },
      seo_title: "Sabor da Casa - Restaurante em Curitiba",
      seo_description: "Restaurante de comida caseira em Curitiba. Buffet por quilo com pratos típicos brasileiros.",
    },
    {
      owner_id: adminId,
      category_id: getCategoryId("advogados"),
      title: "Advocacia Santos & Associados",
      slug: "advocacia-santos",
      description: "Escritório de advocacia especializado em direito civil, trabalhista e empresarial. Mais de 20 anos de experiência. Primeira consulta gratuita.",
      phone_primary: "4135555555",
      phone_whatsapp: "5541955555555",
      email: "contato@santosadvocacia.com.br",
      website: "https://santosadvocacia.com.br",
      address_full: "Rua Visconde de Nácar, 800, 10º Andar, Centro",
      city: "Curitiba",
      state: "PR",
      postal_code: "80410-000",
      status: "active",
      plan_tier: "basic",
      is_verified: true,
      average_rating: 4.6,
      review_count: 38,
      view_count: 560,
      contact_count: 45,
      business_hours: {
        monday: { open: "09:00", close: "18:00" },
        tuesday: { open: "09:00", close: "18:00" },
        wednesday: { open: "09:00", close: "18:00" },
        thursday: { open: "09:00", close: "18:00" },
        friday: { open: "09:00", close: "17:00" },
        saturday: null,
        sunday: null,
      },
      seo_title: "Santos & Associados - Advogados em Curitiba",
      seo_description: "Escritório de advocacia em Curitiba. Direito civil, trabalhista e empresarial. Consulta gratuita.",
    },
  ];

  // Insert listings one by one, ignoring errors for duplicates
  for (const listing of sampleListings) {
    if (listing.category_id) {
      const { error } = await supabase.from("listings").upsert(listing, {
        onConflict: "slug",
        ignoreDuplicates: true,
      });
      if (error) {
        console.error(`Error inserting ${listing.slug}:`, error.message);
      }
    }
  }
}
